#!/usr/bin/perl

use File::Copy;
use Benchmark;
$t0 = new Benchmark;


print "Starting Execution.\n";

$FILE = $ARGV[0];

$home = $ENV{"HOME"};
$EXEC = "$home/modeling/tools/grating/Bscan";
print "Data File : $FILE \n";
print "Cleaning Subdirectories.\n";

if(chdir "./Loaded/1"){
  unlink <*.dat>;
  chdir "../../";
  }
else
  {
  mkdir "./Loaded/1",0777;
  }

if(chdir "./Loaded/1/Near"){
  unlink <*.dat>;
  chdir "../../../";
  }
else
  {
  mkdir "./Loaded/1/Near",0777;
  }

if(chdir "./Loaded/1/Far"){
  unlink <*.dat>;
  chdir "../../../";
  }
else
  {
  mkdir "./Loaded/1/Far",0777;
  }

if(chdir "./Unloaded"){
  unlink <*.dat>;
  chdir "../";
  }
else{
  mkdir "./Unloaded", 0777;
  }

if(chdir "./OMB/1"){
  unlink <*.dat>;
  chdir "../../";
  }
else{
  mkdir "./OMB/1", 0777;
  }

system("$EXEC -B1 -G -L -F -P1230 -S -N40  $FILE | tee out");

$t1 = new Benchmark;
$td = timediff($t1, $t0);

print "Execution times: ", timestr($td), "\n";
